sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vinothr90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinothr90/react-test npm test -- --coverage

after_success:
  - docker build -t vinothr90/multi-client ./client
  - docker build -t vinothr90/multi-nginx ./nginx
  - docker build -t vinothr90/multi-server ./server
  - docker build -t vinothr90/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vinothr90/multi-client
  - docker push vinothr90/multi-nginx
  - docker push vinothr90/multi-server
  - docker push vinothr90/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-115774086905"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
